name: LStaffChat
version: '1.0'
main: com.uaulight.lstaffchat.Main
authors: [ uauLight ]
description: Plugin de chat staff para o seu servidor.
website: https://skymc.com.br/
commands:
  staff:
    aliases: [s,staffchat]